### ISSUE TITLE
[Arch linux]Wifi config hangs when selected

### ISSUE THREAD

**Issue by heavysink** [Arisotura/melonDS#532] opened 2019-10-27 18:11 UTC
Environment: Archlinux
Version:melonds git

Config->Wifi settings, console output libpcap.so.1 init successful and then hangs

**Comment by i404788** [comment] 2019-11-19 21:32
Had same issue on ubuntu, seems to be caused by active devices with `null` addresses.

**Comment by Arisotura** [comment] 2019-11-20 21:46
oops. my bad

**Comment by WaluigiWare64** [comment] 2021-02-02 16:23
Was fixed in the PR that linked here.

**Closed by WaluigiWare64** 2021-02-02 16:23 UTC
