### ISSUE TITLE
no paramater exsists for fullscreening the emulator from bootup

### ISSUE THREAD

**Issue by derric-young** [Arisotura/melonDS#1334] opened 2022-01-07 11:48 UTC
no paramater exsists for fullscreening the emulator from bootup
the paramater could be -fullscreen or other such. when it is added. tell me either though here (like a sane person world do) or though discord by direct messaging derric young#7856 (version used. 0.9.2. does not exsist as far as im aware of version 0.9.3. should come in version 0.9.4 or 1.0.0)

**Comment by RayyanAnsari** [comment] 2022-01-07 11:51
duplicate of https://github.com/Arisotura/melonDS/issues/1108

**Closed by RayyanAnsari** 2022-01-07 11:51 UTC
