### ISSUE TITLE
Choosing the "Shut down" option in the BIOS menu should cause it to shut down

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#880] opened 2020-12-22 07:35 UTC
As of now it fades out a bit and stays frozen.

![Capture](https://user-images.githubusercontent.com/68873449/102861927-76891800-4484-11eb-91d4-1dfc3093b6c5.PNG)

**Comment by RSDuck** [comment] 2021-01-25 17:05
duplicate of https://github.com/Arisotura/melonDS/issues/639

**Closed** 2021-01-26 15:43 UTC
