### ISSUE TITLE
Yu-Gi-Oh 5DS Over the Nexus 2011 desyncs in local wireless emulation

### ISSUE THREAD

**Issue by SuperShesh2** [Arisotura/melonDS#1157] opened 2021-07-15 04:14 UTC
System: Windows 10
melonDS version: 0.9.2

Issue: Local Wireless Duel desyncs randomly, making duels impossible to complete.

Steps to reproduce:
- Generate two empty save files for the game (no completion necessary for reproduction)
- Connect to DS Local Wireless in the game with both connected on the same computer running two instances of MelonDS.
- Go into a Deck Rental duel with two decks.
- Duel until desync happens (sometimes will happen at the start, sometimes it will be a few turns in)

Notes: I don't know if something is dropping some signals somewhere causing the ingame desyncs, or if its lag in the game.

**Comment by RSDuck** [comment] 2021-07-15 04:18
known issue. Local wireless is unfortunately unstable in all games. Try disabling the frame limiter and audio sync, that can help, though there are still issues (besides the game running too fast).

**Comment by SuperShesh2** [comment] 2021-07-15 07:25
I apologize for wasting time with a known issue.

**Comment by akirataguchi115** [comment] 2021-07-19 06:21
@RSDuck Are the frame limiter and audio sync tips documented somewhere?

If so @SuperShesh2 maybe close this issue? 🐱

**Closed** 2021-07-20 17:23 UTC

**Comment by RSDuck** [comment] 2021-07-20 17:30
> @RSDuck Are the frame limiter and audio sync tips documented somewhere?

not really, it's mostly just lamenting knowledge (I forgot the proper word for this) and neither a solution, more a bad workaround. Though the issue really just exists with every game which uses local wireless, it's just a very fundemental problem.

**Comment by SuperShesh2** [comment] 2021-07-20 17:55
is there any testing that would help in figuring out how it works better? I have a couple ds's but I guess the issue is reading the wireless signals between them not really having the hardware

**Comment by RSDuck** [comment] 2021-07-20 18:04
nah that's not the issue. The problem is known when there's a frame limiter in place what's done is that one frame is emulated as fast as your computer can do it and then melonDS sleeps until the target frame time is reached (1/60s~16.6ms). If you have two instances on the same computer running and you're computer is fast enough so the window where melonDS is sleeping is large enough both instances can "miss" each other.

The solution would be to have some kind of explicit synchronisation between all instances, but the details are yet to be found out.

**Comment by SuperShesh2** [comment] 2021-07-20 18:24
oh the *sleeping* is the issue. That makes a lot of sense. And that synchronization would likely be difficult to get working smoothly and also slow things down from the very little I know of emulation implementation.
