### ISSUE TITLE
[Feature Request] Reading ROMs inside of ZIP and 7z archives

### ISSUE THREAD

**Issue by Aluminite** [Arisotura/melonDS#453] opened 2019-06-16 13:25 UTC
Some other emulators like DeSmuME support this. With DS ROMs having so much wasted space in them, this would be really useful.

**Comment by cascardian** [comment] 2019-06-16 15:57
GZIP support specifically would probably be the most useful, given its impressive compression rates (it's also used in PCSX2 and DeSmuME, e.g.).

**Comment by githuborer** [comment] 2019-06-20 14:44
Most important for me would be 7zip support bc of compress rate

**Comment by nathanielcwm** [comment] 2019-06-21 05:27
There was a pr that was supposed to do that iirc

**Comment by nathanielcwm** [comment] 2019-06-21 05:28
#364

**Comment by Arisotura** [comment] 2019-06-21 12:18
yup. I need to add in a proper base so we don't need to add libarchive stuff into the core.

also, this asks a bunch of questions, like, where should savegames/etc go?

**Comment by githuborer** [comment] 2019-06-28 13:20
Lets configure savegames/etc paths from melonDS settings

**Comment by Arisotura** [comment] 2019-06-28 23:37
yeah, but like

default behavior is to put the save file alongside teh ROM. if the ROM is in a zip, I guess we would put the savefile alongside the zip.

then it could be configured, with a given path, and "relative to ROM / relative to melonDS"

**Comment by githuborer** [comment] 2019-07-02 18:08
Often those packed rom collections (like mine) are stored on a read-only nas storage ;)

**Comment by RinMaru** [comment] 2020-08-14 07:33
huh this hasn't been implemented yet?

**Comment by poudink** [comment] 2020-08-15 03:29
clearly not. there's a PR (https://github.com/Arisotura/melonDS/pull/678) open about it though.

**Comment by nathanielcwm** [comment] 2020-10-22 13:01
btw dupe of 203

**Comment by WaluigiWare64** [comment] 2021-01-23 17:47
melonDS supports reading numerous archive formats in latest master.

**Closed by WaluigiWare64** 2021-01-23 17:47 UTC
Labels: enhancement
