### ISSUE TITLE
Mic doesn't work in DSi mode

### ISSUE THREAD

**Issue by HilbertIdeals5** [Arisotura/melonDS#1263] opened 2021-11-24 01:15 UTC
As the title says. This issue is in melonDS 0.9.3, the stable release. When I go to Mic Test in the DSi System Settings or in Pokemon Black 2, there's no indicator animation. I have my mic set to "External Microphone", which works fine on DS mode.

**Comment by nadiaholmquist** [comment] 2021-11-24 01:22
The way the mic works on the DSi is a bit different from the original DS, I'm not sure if this has been implemented yet.

The mic should work in BW2 if you set it to DS mode in the meantime.

**Comment by RayyanAnsari** [comment] 2021-11-24 07:57
duplicate of #726

**Closed by RayyanAnsari** 2021-11-24 07:57 UTC
Labels: DSi
