### ISSUE TITLE
Problems with time based events in Pokémon Platinum

### ISSUE THREAD

**Issue by ghost** [Arisotura/melonDS#443] opened 2019-06-10 13:48 UTC
I have test using the current release 0.8 and the previous one that events where the time is used doesn't work properly. 
For example, the growth of berries and the Drifloon event which happens only on Friday.
For the latter example I found that if you change the Windows clock to Friday while running the emulator with the game the event now occurs.

I haven't tested it in my linux box yet sorry. 

Can It be due to Windows autosyncing the clock from a NTP server? Or it's an already know behavior? I'm sorry if repost but I haven't found a similar issue.

I don't know if or how can  I get some logs but if they are necessary just tell me

**Comment by Arisotura** [comment] 2019-06-10 14:15
that's normal behavior, melonDS just reads the system time

**Comment by Turbito** [comment] 2019-06-10 14:37
the workaround would be disable Windows to ajust the time?

**Comment by Arisotura** [comment] 2019-06-10 18:28
what??

**Comment by Turbito** [comment] 2019-06-10 19:37
sorry I thought it was a problem with the clock resyncing
It is can be fix sometime or it's out of scope? I don't know very much about emulator programming, sorry!

**Comment by Arisotura** [comment] 2019-06-10 21:41
we might eventually make melonDS do its own time-keeping, not quite sure how to proceed tho

**Comment by Ammako** [comment] 2019-06-13 03:08
> we might eventually make melonDS do its own time-keeping, not quite sure how to proceed tho

Maybe you meant this in more of a "not sure how to implement it" kind of way, but just in case, I figured it would be worth bringing [this](http://melonds.kuribo64.net/board/thread.php?pid=971#971) up again (if anything, the issue has better visibility on Github, anyway, and it'll be easier to track everything related to it on here.)

For everyone else, I'm fairly certain that melonDS simply doesn't handle RTC correctly, in a way where time advances as normal and no glitches happen, but games interpret the computer's time passing while the game is closed, as you having changed the clock on the DS. The reason why it works if the clock passes midnight while in-game, is because, this is actually the expected behavior: it works like that on real hardware, too. You can bypass the anti time cheat on most time-based events by setting your DS's clock to 11:59, then quickly starting the game and loading your save file, and letting the clock roll over to midnight while in-game. On emulator, changing your system's clock while the game is running has the same effect (I guess the game is simply not equipped to detect the clock being tampered with while it's currently running, which makes sense, because there is no way to do this on real hardware anyway.)

**Comment by Arisotura** [comment] 2019-06-13 10:07
"but games interpret the computer's time passing while the game is closed, as you having changed the clock on the DS."

well, dunno? the same would happen on the DS, that's the point of having a RTC

**Comment by Ammako** [comment] 2019-06-13 15:00
Changing the clock on the DS --> firmware rtc offset is modified --> games can notice this and activate their anti time cheat mechanism.

Letting time pass normally --> firmware rtc offset is left untouched --> time passes as normal and games work as normal

**Comment by Ammako** [comment] 2019-06-13 16:46
I think I understand where the confusion is coming from. It seems to be true that the DS doesn't actually use the offset in order to display the time, it just displays the time according to the raw rtc. However, changing the time through the system settings does something with the firmware rtc offset, and games with anti time-travel mechanisms rely on that value in order to determine whether the time was tampered with. There is no other way that the games could be detecting a difference between time passing normally, and time being tampered with through the system settings. It works the same way on the DSi and 3DS, except the 3DS at least displays the time according to the firmware rtc offset. Not sure about the DSi, haven't checked yet.

You have experience writing NDS homebrew, do you think you'd be able to write a simple homebrew which only reads and displays the current firmware rtc value? I think that would be a lot of help, because then you could use this to determine what happens when the time is changed in the DS settings, vs what happens when you just let the time pass normally. If the firmware rtc offset value changes every time you change the time in the DS settings, but always remains the same for as long as you never touch DS settings, then that would indicate that the firmware rtc offset needs to remain constant in order to avoid tripping up games' anti time-travel mechanism. If, against my expectations, it behaves differently, then at the very least, it'll offer some insight as to what happens with that offset value, and it might help with figuring out exactly how to avoid tripping up said anti time-travel mechanism.

I remain open to the possibility that I'm completely wrong, and that the games actually rely on something completely different to keep track of time being tampered with, but if that's the case, then I am at a loss as to what else it could be. I have no experience with writing DS homebrew, but I have a lot of free time, so if you're busy, then I'd probably be able to learn how to write simple homebrew, and make that app myself, so I could check all of this stuff.

**Comment by Arisotura** [comment] 2019-06-14 14:05
I guess I'd have to test it.

but, regardless, melonDS does not touch the RTC offset value at all, unless you attempt to change the current date/time in the firmware (noting that doing so might change the RTC offset, but aside from that, doesn't achieve anything).

**Comment by Ammako** [comment] 2019-06-14 14:47
Purely a wild guess, but does melonDS allow the games to read this value
(or does it at least provide games with a pre-defined value, when they do
attempt to read that value)?

I wonder if it's possible that the games attempting to read it, but
failing, could cause the anti time-travel to trigger, as some kind of
safeguard.

It does work fine in DeSmuME, so hopefully its source code could provide
some insight in how they make it work.

**Comment by Ammako** [comment] 2019-06-14 14:55
It could be that rtc was a red herring, and it's your mac address randomization thingy causing the problems.

**Comment by Ammako** [comment] 2019-06-14 15:14
Yep. I can confirm on real hardware that, even if the rtc offset is the same, as long as the mac address differs, time-based events break, for games that have anti time-travel functions.

I must apologize for my insistence on the rtc offset being the issue. I have no idea why they'd go as far as checking the mac address, considering that the rtc offset is pretty unlikely to ever match up on two different consoles (outside of hacking), but I guess they wanted to make absolutely sure that playing on a different DS would trip up the anti time-travel.

**Comment by Arisotura** [comment] 2019-06-14 19:39
berp. what a pile of dickwads.

now I have to think of a solution for this. thanks a-plenty, DerpoCo game dev.

blarg

**Comment by JMC47** [comment] 2019-06-26 20:53
In regards to the time issue, Dolphin provides a pretty simple to implement solution that you could put in the GUI.  By default, use system time, but also give an option to "override" the system time with a specific time/date.

![image](https://user-images.githubusercontent.com/6598209/60214135-e9371a00-9832-11e9-90e2-451e1d46ce25.png)

**Comment by ashelleyPurdue** [comment] 2020-01-10 00:17
> It does work fine in DeSmuME, so hopefully its source code could provide some insight in how they make it work.

What version of DeSmuME are you using?  I'm using version #be2735b3, and I'm getting the exact issues you're describing.  Perhaps Desmume changed something in this version that broke the time mechanics?

**Comment by RSDuck** [comment] 2022-07-28 10:19
Not an issue if MAC randomization is disabled.

**Closed by RSDuck** 2022-07-28 10:19 UTC
