### ISSUE TITLE
Music skips during scene changes in Chrono Trigger and Castlevania: Order of Ecclesia

### ISSUE THREAD

**Issue by yuriks** [Arisotura/melonDS#92] opened 2017-07-13 06:15 UTC
In both games, the game music skips forward (with no apparent crackling or buffering issues, it just skips forward a bit) by about a second when a new room/screen is entered. In Chrono Trigger this happens reliably when entering an area map coming from the world map. In Order of Ecclesia it happens sometimes when changing between certain screens.

There isn't any host-side CPU spike or slowdown in these situations, so it might be related to loading data from the cart?

**Comment by StapleButter** [comment] 2017-07-13 21:00
Which melonDS version? 0.3 had an ARM7 DMA timing bug that mostly affected cart transfers.

**Comment by yuriks** [comment] 2017-07-13 21:10
This is with the pre-0.4 build you sent me before. I'm not sure which commit that is from.

**Comment by yuriks** [comment] 2017-07-14 07:11
Found a super easy way to reproduce this in Order of Ecclesia: Just Repeatedly entering and exiting the menu will cause a skip, so it's super easy to notice if you just repeatedly mash start while in-game.

**Comment by StapleButter** [comment] 2018-12-21 14:08
can you (or someone else) test this again pls?

**Comment by yuriks** [comment] 2019-01-02 00:07
I'll test it when I'm back home in ~a week.

**Comment by DarkSwan86** [comment] 2020-09-05 13:38
Seem fixed on 0.9 on Castlevania OoE (E), can you check it?

**Comment by poudink** [comment] 2020-09-18 00:39
I can't say for Chrono Trigger, but as far as Castlevania is concerned, this was indeed fixed in melonDS 0.7.1

**Comment by a-vrma** [comment] 2021-01-01 00:25
I tried leaving and entering the Manolia Cathedral in Chrono Trigger using melonDS 0.9.1 on Linux and I can't reproduce the bug.

Are you able to reproduce @yuriks?

**Comment by a-vrma** [comment] 2021-01-05 19:10
Never mind the last comment. The skip, which is fairly subtle, occurs when entering and exiting some areas but not others. I was able to reproduce on a brand new save just entering and exiting my own house.

**Comment by Arisotura** [comment] 2021-11-23 18:02
can you test this again on the latest revision?

**Comment by yuriks** [comment] 2021-11-23 18:03
oops, sorry for forgetting about this. I'll re-test in a few minutes

**Comment by yuriks** [comment] 2021-11-26 00:55
Just tested on 0.9.3 and I can't reproduce any of the audio skips I'd mentioned before. So as far as I can tell this seems to be fixed!

For future reference, I went back and bisected the fix. It appears that 0.7 still had the issue, but it's not present in 0.7.1 or in several later versions I also tested.

**Closed** 2021-11-29 19:11 UTC
