### ISSUE TITLE
[Request] Map control stick of a controller to the touchscreen

### ISSUE THREAD

**Issue by EnterpriseFreak-v2** [Arisotura/melonDS#1231] opened 2021-09-28 18:30 UTC
It would be nice to have an option that allows one to map the stick of a controller to the touchscreen, some games like Super Mario 64 DS could really profit from that as it would allow for more precise controls.

**Comment by RayyanAnsari** [comment] 2021-09-28 18:40
duplicate of #1206

**Closed by RayyanAnsari** 2021-09-28 18:40 UTC
