### ISSUE TITLE
[Feature Request] Option for dedicated save folder

### ISSUE THREAD

**Issue by Stevoisiak** [Arisotura/melonDS#1074] opened 2021-04-25 01:57 UTC
Currently melonDS creates save files in the same folder the ROM is loaded from. I'd be nice to have an option to configure a dedicated save folder, so games can be separated from ROMs.

**Comment by RSDuck** [comment] 2021-04-25 02:01
duplicate of #338

**Closed by RSDuck** 2021-04-25 02:01 UTC
