### ISSUE TITLE
[SW/OpenGL] Pokemon B/W/B2/W2 Entering A Pokemon Battle Cause This To Happen

### ISSUE THREAD

**Issue by RianCaio** [Arisotura/melonDS#474] opened 2019-06-25 21:07 UTC
![Screenshot_5](https://user-images.githubusercontent.com/44629452/60133643-1a9ce080-9774-11e9-8352-14a0601b3bff.jpg)

**Comment by Arisotura** [comment] 2019-06-25 23:30
so?

**Comment by RianCaio** [comment] 2019-06-25 23:39
Its Supost To Do A Zoom Not Appearing A Black Kyurem

**Comment by Arisotura** [comment] 2019-06-26 11:25
would you have a screenshot of what it's supposed to look like?

**Comment by Ammako** [comment] 2019-06-26 23:34
[Broken](https://gfycat.com/secondarypinkgrouper)

[Not broken](https://gfycat.com/sparklingsimplebuffalo)

**Comment by Ammako** [comment] 2019-06-26 23:35
Worth noting that the title screen legendary's model only shows up for the first wild battle of the session, every time afterwards behaves as I've shown.

**Comment by ketsuban** [comment] 2020-09-05 21:30
What image is used for the effect seems to be based on your recent ingame actions. The first wild battle of a session uses a picture of the Kyurem model on the title screen, but if you enter and exit a building like the ones in Accumula Town then the next wild battle will use a snapshot of you exiting the building.

**Comment by RSDuck** [comment] 2020-09-05 22:35
this is confirmed to be an ARM9 timing issue. Works with the arm9timinghack branch

**Comment by RSDuck** [comment] 2020-12-09 21:48
apparently this wasn't a timing issue after all, but something was missing in our display capture implementation. Closed in https://github.com/Arisotura/melonDS/commit/e34ce013dfc10ccf80c34ef5b1f5f3c69059c1e2

**Closed by RSDuck** 2020-12-09 21:48 UTC
Labels: OpenGL, timing

**Comment by CodingKoopa** [comment] 2020-12-10 00:05
Thank you for the fix!
