### ISSUE TITLE
Graphics are broken when built with Clang

### ISSUE THREAD

**Issue by HilbertIdeals5** [Arisotura/melonDS#944] opened 2021-01-15 20:37 UTC
When I set the melonDS to the DS console type and boot to firmware, the top screen is black:

<img width="368" alt="Screen Shot 2021-01-15 at 3 31 35 PM" src="https://user-images.githubusercontent.com/63978875/104775949-3ba69700-5747-11eb-8732-36b24f7353f1.png">

It fades to white during transitions, but otherwise stays blank:

<img width="368" alt="Screen Shot 2021-01-15 at 3 32 49 PM" src="https://user-images.githubusercontent.com/63978875/104775989-4d883a00-5747-11eb-8445-5e6f84d70131.png">

Also, for some reason, opening PictoChat makes the top screen green:

<img width="368" alt="Screen Shot 2021-01-15 at 3 32 02 PM" src="https://user-images.githubusercontent.com/63978875/104776021-5da01980-5747-11eb-9691-743f6cb9d1b6.png">

I'm on macOS 11 Big Sur. The device is a MacBook Air (M1, 2020).

**Comment by RSDuck** [comment] 2021-01-15 20:39
OpenGL renderer or software renderer?

**Comment by WaluigiWare64** [comment] 2021-01-16 10:45
Could you try building with
`-DCMAKE_BUILD_TYPE=Debug`?

**Comment by HilbertIdeals5** [comment] 2021-01-16 22:22
1. Software renderer, macOS doesn't have OpenGL so I didn't change the setting.
2. Yes, this is through Rosetta 2.
3. ......b-b-build? I don't know if I should do that...

**Comment by WaluigiWare64** [comment] 2021-01-17 22:43
Right, so we are investing the issue. Looks like there was a regression somewhere. melonDS doesn't seem to load the top screen correctly for some reason if it was built using Clang in release mode (even on Linux). However, it seems to work in Debug mode. We'll have to bisect the issue.
Meanwhile, could you test the melonDS for macOS beta? It seems to be working fine there.

**Comment by StLouisCPhT** [comment] 2021-01-18 01:02
> Meanwhile, could you test the melonDS for macOS beta? It seems to be working fine there.

It works fine with on macOS as long as it is built with -DCMAKE_BUILD_TYPE=Debug or -DCMAKE_BUILD_TYPE=Release
If the build type is not specified, that is when the graphic issues occur.

**Comment by StLouisCPhT** [comment] 2021-01-18 01:06
> Right, so we are investigating the issue. Looks like there was a regression somewhere. melonDS doesn't seem to load the top screen correctly for some reason if it was built using Clang in release mode (even on Linux). However, it seems to work in Debug mode. We'll have to bisect the bug.
> Meanwhile, could you test the melonDS for macOS beta? It seems to be working fine there.
> http://melonds.kuribo64.net/comments.php?id=129

Are you sure?  It works fine for me on macOS when built as Debug and Release. If the build type is not specified, that is when the graphic issues occur.

**Comment by StLouisCPhT** [comment] 2021-01-18 01:07
> * Software renderer, macOS doesn't have OpenGL so I didn't change the setting.

macOS does have OpenGL, it's just frozen at 4.1.

**Comment by WaluigiWare64** [comment] 2021-01-18 09:15
> 
> 
> > Right, so we are investigating the issue. Looks like there was a regression somewhere. melonDS doesn't seem to load the top screen correctly for some reason if it was built using Clang in release mode (even on Linux). However, it seems to work in Debug mode. We'll have to bisect the bug.
> > Meanwhile, could you test the melonDS for macOS beta? It seems to be working fine there.
> > http://melonds.kuribo64.net/comments.php?id=129
> 
> Are you sure? It works fine for me on macOS when built as Debug and Release. However, if the build type is not specified, that is when the graphic issues occur.

But in CMakeLists.txt, if no build type is specified, it automatically sets BUILD_TYPE to Release.
https://github.com/Arisotura/melonDS/blob/d529b650c06a4dd43904dfead49011be1ba9db9a/CMakeLists.txt#L24-L26

**Comment by WaluigiWare64** [comment] 2021-01-18 10:25
So I've found the commit which caused the regression: https://github.com/Arisotura/melonDS/commit/6e8bac39091d0321f43a3e7574d3359255996e9f
I'm currently waiting on a response from @RSDuck.

**Comment by StLouisCPhT** [comment] 2021-01-18 15:10
> > > Right, so we are investigating the issue. Looks like there was a regression somewhere. melonDS doesn't seem to load the top screen correctly for some reason if it was built using Clang in release mode (even on Linux). However, it seems to work in Debug mode. We'll have to bisect the bug.
> > > Meanwhile, could you test the melonDS for macOS beta? It seems to be working fine there.
> > > http://melonds.kuribo64.net/comments.php?id=129
> > 
> > 
> > Are you sure? It works fine for me on macOS when built as Debug and Release. However, if the build type is not specified, that is when the graphic issues occur.
> 
> But in CMakeLists.txt, if no build type is specified, it automatically sets CMAKE_BUILD_TYPE to Release.
> 
> https://github.com/Arisotura/melonDS/blob/d529b650c06a4dd43904dfead49011be1ba9db9a/CMakeLists.txt#L24-L26

Oh, that explains it. This is a known issue with Cmake & CMakeLists, going back at least 6 years.
https://stackoverflow.com/questions/24460486/cmake-build-type-is-not-being-used-in-cmakelists-txt 

> So I've found the commit which caused the regression: [6e8bac3](https://github.com/Arisotura/melonDS/commit/6e8bac39091d0321f43a3e7574d3359255996e9f)
> I'm currently waiting on a response from @RSDuck.

Dirty ram tracking casing the issue? That's dirty pool indeed.

I wonder though if it is also an issue with cmake not

**Comment by HilbertIdeals5** [comment] 2021-01-20 18:59
> Right, so we are investigating the issue. Looks like there was a regression somewhere. melonDS doesn't seem to load the top screen correctly for some reason if it was built using Clang in release mode (even on Linux). However, it seems to work in Debug mode. We'll have to bisect the bug.
> Meanwhile, could you test the melonDS for macOS beta? It seems to be working fine there.
> http://melonds.kuribo64.net/comments.php?id=129

I was actually using that same binary before melonDS 0.9.1, and it was fine. It seems like this comment is pretty late though.

**Comment by HilbertIdeals5** [comment] 2021-02-07 21:46
I'm reverting back to melonDS 0.9 for the time being.

**Comment by RSDuck** [comment] 2021-02-09 18:29
fixed in https://github.com/Arisotura/melonDS/commit/6256a42e0099cef9f567148083c55bbb798d8184

**Closed by RSDuck** 2021-02-09 18:29 UTC
