### ISSUE TITLE
Save threading

### ISSUE THREAD

**Issue by ichee** [Arisotura/melonDS#810] opened 2020-11-11 11:43 UTC
Whenever a game is saved, a brief, but noticeable, stutter occurs.

The save process should instead be handled in a separate thread, or possibly asynchronously, to avoid such issue.

Disk is a SSD NVME.

Windows 10

**Comment by RSDuck** [comment] 2020-11-11 12:02
duplicate of #477

**Comment by ichee** [comment] 2020-11-12 09:25
Seems to be fixed in 62e3f41.

Tested game was Castlevania Dawn of Sorrow.

**Closed** 2020-11-12 09:25 UTC
Labels: duplicate
