### ISSUE TITLE
(DSi) TLoZ: Four Swords Anniversary Edition: broken graphics

### ISSUE THREAD

**Issue by v1993** [Arisotura/melonDS#733] opened 2020-08-31 14:28 UTC
It could be a bit hard to describe, but this picture says it all:

![Screenshot_20200831_171606](https://user-images.githubusercontent.com/16255906/91730209-56200f80-ebae-11ea-8093-07edf4c7ea14.png)

As you can see, it is essentially unplayable in this state.

To reproduce, simply boot the game, create a save file, start sinleplayer mode and enter the first stage. This issue is present both on software and OpenGL renderers, on both 1x and higher resolutions on later. JIT is obviously turned off.

**Comment by Pik-a-boo** [comment] 2020-08-31 18:18
Same issue as no$gba btw.

**Comment by poudink** [comment] 2020-08-31 19:20
Wonder what the cause is. Does the DSi have any differences on the GPU side?

**Comment by Arisotura** [comment] 2020-09-02 11:05
are you playing this from a ROM, or DSiware?

**Comment by v1993** [comment] 2020-09-02 12:08
@Arisotura This game is DSiware-exclusive. I'm loading it from `.nds` file, originally extracted from CIA IIRC.

**Comment by Arisotura** [comment] 2020-09-02 12:14
the game might be hardwired to load some assets from NAND. regardless, I'd interested into taking a loook -- anyway I can obtain the ROM for a test?

**Comment by v1993** [comment] 2020-09-02 14:08
@Arisotura How can I send you ROM?

Additionally, I've also tested this with booting game directly from NAND DSi dump, with the same results.

**Comment by Arisotura** [comment] 2020-09-02 14:11
I got the ROM already, but thanks

**Comment by Arisotura** [comment] 2020-09-02 14:27
well, I emailed you

**Comment by Arisotura** [comment] 2020-09-03 08:34
had a look at this. it appears that whatever graphics should be transferred when entering the level, aren't being transferred. this is going to be a pain to debug (it's always harder when it's something not being copied at all, as you don't really have a base for knowing where/how it should happen, and DS/DSi code is too complex to attempt tracking this manually)

**Comment by Arisotura** [comment] 2020-09-03 09:31
holy shit. the game is trying to write to VRAM in 8-bit units.

I vaguely recall there was something in the DSi that enabled doing so... gonna check that.

**Closed** 2020-09-03 09:52 UTC
