### ISSUE TITLE
Pokemon HeartGold flickering black dotted lines OpenGL

### ISSUE THREAD

**Issue by freezethekid** [Arisotura/melonDS#1049] opened 2021-04-01 18:40 UTC
I believe this was a common issue on Pokémon games in OpenGL on desmume, but it was fixed later.

![blackdots](https://user-images.githubusercontent.com/81773189/113339148-0d713600-92f8-11eb-9c32-168e13c8d8fc.PNG)

**Comment by RSDuck** [comment] 2021-04-01 18:42
duplicate of #458

**Closed by RSDuck** 2021-04-01 18:42 UTC
