### ISSUE TITLE
Crash when booting firmware

### ISSUE THREAD

**Issue by loffren174** [Arisotura/melonDS#1386] opened 2022-03-09 18:24 UTC
First of all, thanks to everyone for the awesome, feature-packed new release!

I'm using the AUR package of melonDS, on linux manjaro: https://aur.archlinux.org/packages/melonds
I mention that because I'm not sure whether it's a build issue.

In melonDS 0.9.3, I could boot a DS firmware without issues to full functionality, changing name, settings, language etc. 
In melonDS 0.9.4, when attempting to boot the dumped firmware of my DS lite, it locks up for a split second then closes with the following crash/error message:

```
$ melonDS
melonDS 0.9.4
https://melonds.kuribo64.net/
libpng warning: iCCP: known incorrect sRGB profile
Audio output frequency: 48000 Hz
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1639, resource id: 11760473, major code: 40 (TranslateCoords), minor code: 0
ARM9 BIOS loaded
ARM7 BIOS loaded
Resetting JIT block cache...
done resetting jit mem
done resetting jit mem
MAC: 00:16:56:83:31:F9
FW: WIFI CRC16 = GOOD
FW: AP1 CRC16 = GOOD
FW: AP2 CRC16 = GOOD
FW: AP3 CRC16 = GOOD
FW: USER0 CRC16 = GOOD
FW: USER1 CRC16 = GOOD
/usr/include/c++/11.2.0/bits/basic_string.h:1058: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Abgebrochen (Speicherabzug geschrieben) (German, translated: 'Aborted. Wrote memory dump.')
```

This happens in all combinations of 'override firmware settings' checked/unchecked, and 'JIT compile' checked/unchecked.
When using said firmware to play a game (disabling the 'override firmware settings' setting) the game ROM works same as with melonDS 0.9.3.

The error message says something about a 'memory dump', but I can't find information on where that dump is written to. I've looked in all system folders, tmp, var, log, the home directory, melonDS config directory, but I didn't find any log relating to it. If it helps (and someone gives me hints where to find it) I can gladly provide that.

Regarding reproducibility, my dumped firmware's checksums seems remarkably similar to /nintendo-ds-firmware other people have dumped and archived. I also have two other NDS Lite systems and a homebrew cartridge so I could dump their firmware/bios and test them if needed.

**Comment by RayyanAnsari** [comment] 2022-03-09 18:34
I don't get this error - try building melonDS from source (there are instructions in the README).

**Comment by loffren174** [comment] 2022-03-09 18:47
> I don't get this error - try the melonDS 0.9.4 release on the website.

When using the compiled x64 linux release from the website, the error does not occur. The firmware can be booted without any problems, settings changed etc, which propagate to the game ROM when booted with the firmware selected. Everything works.

Any ideas on how to pinpoint the error so I know who to contact?

**Comment by RayyanAnsari** [comment] 2022-03-09 19:34
you should just contact the maintainer of that package and reference this issue.

**Comment by nadiaholmquist** [comment] 2022-03-09 19:38
This issue is fixed but it seems the tag has not been changed to the commit that fixes it, which is right after the commit the tag currently references.

For now use melonds-git instead.

**Comment by loffren174** [comment] 2022-03-09 19:40
> you should just contact the maintainer of that package and reference this issue.

Left a comment to the maintainer. I think people can still comment on closed issues if more information is required, right? So I'll close this issue. 

> This issue is fixed but it seems the tag has not been changed to the commit that fixes it, which is right after the commit the tag currently references. For now use melonds-git instead.

Oops, I read that message just when I had commented already on the package. Not sure what to tell them, but the information is in this issue either way, which I linked there.

Thanks to everyone for the speedy response!

**Comment by RayyanAnsari** [comment] 2022-03-09 19:42
yeah, the issue is because we haven't updated our 0.9.4 tag on github.

**Comment by loffren174** [comment] 2022-03-09 20:16
I have edited my comment on the repo build with this information so hopefully noone panics there. I don't think many people will boot their firmware anyway to notice this behavior, even less after this version comes with a builtin one.

**Comment by RayyanAnsari** [comment] 2022-03-09 20:16
this should be fixed, try rebuilding the aur package again

**Comment by loffren174** [comment] 2022-03-09 20:51
It seems that the version name used in the package is indeed now 0.9.4-1. Since I can't figure out how to manually run the AUR's package script and my mirrors take their time updating, I simply built melonDS myself instead with the tag that's currently used by the package script (which is `git+https://github.com/Arisotura/melonDS.git#tag=0.9.4` )
So I used `git clone -b '0.9.4' https://github.com/Arisotura/melonDS` and then built it according to the readme instructions. (which is what the package script does anyway)

Then I ran all tests again, and everything works. Excellent!

**Comment by nadiaholmquist** [comment] 2022-03-09 20:52
```
git clone https://aur.archlinux.org/melonds.git
cd melonds
makepkg -i
```

**Comment by loffren174** [comment] 2022-03-09 21:13
trying to boot firmware with...

the build I manually got from the branch: works
the package script from AUR: works (mirrors are updated now).
the build I made with these commands you provided: works.
```
git clone https://aur.archlinux.org/melonds.git
cd melonds
makepkg -i
```
(of course I uninstalled each build after testing so only the currently testing one could be used.)

I guess that triple-confirms this fixed! :D

**Closed** 2022-03-09 21:34 UTC
