### ISSUE TITLE
(OpenGL) Pokemon Black/White - texture artifacting in several areas

### ISSUE THREAD

**Issue by Abbanon** [Arisotura/melonDS#1383] opened 2022-03-05 02:00 UTC
As the title suggests, I've found a few glitchy areas in Pokemon White(/Black) when using the OpenGL renderer.
I'll likely be adding onto this post as I discover more, for the sake of documentation.
MelonDS build used: https://github.com/Arisotura/melonDS/actions/runs/1935614942

-----
Route 9 (OpenGL)
![(OpenGL) Pokemon White - Route 9](https://user-images.githubusercontent.com/37251822/156862966-f31b7136-887a-4f65-b4bf-ba4c2c21e653.png)

Route 9 (Software)
![(Native) Pokemon White - Route 9](https://user-images.githubusercontent.com/37251822/156862995-5d2aecab-d24c-4b58-bff1-4df9265e7559.png)

-----
Driftveil City (OpenGL)
![(OpenGL) Pokemon White - Driftveil City](https://user-images.githubusercontent.com/37251822/156863206-ecb72e50-e660-4b7b-a9f5-7a59fac857c8.png)

Driftveil City (Software)
![(Native) Pokemon White - Driftveil City](https://user-images.githubusercontent.com/37251822/156863224-2c20af67-6876-409b-8600-7ac09c922a41.png)

-----

**Comment by Brankale** [comment] 2022-03-05 12:15
duplicate of #712

**Closed** 2022-03-06 14:55 UTC
