### ISSUE TITLE
Emulation doesn't resume when pausing is enabled.

### ISSUE THREAD

**Issue by nathanielcwm** [Arisotura/melonDS#1053] opened 2021-04-06 03:02 UTC
d5dbef2c22f755ad82ec59e04948111797bc270a

When `Pause emulation when window is not in focus` is enabled it doesn't resume the emulation when you navigate back to the melonDS window.

Only reset seems to fix the issue but savestates can still be created and used after the reset.

**Comment by WaluigiWare64** [comment] 2021-04-25 12:14
I can't reproduce this.
What OS are you using?

**Comment by nathanielcwm** [comment] 2021-04-25 12:15
Windows 10

**Comment by WaluigiWare64** [comment] 2021-04-25 12:16
hmm...
Could you make a video? I'm on Windows 10 too.

**Comment by nathanielcwm** [comment] 2021-04-26 01:04
https://youtu.be/KBWNKW5PHnM

**Comment by WaluigiWare64** [comment] 2021-04-26 21:17
Could you provide the ini file?

**Comment by nathanielcwm** [comment] 2021-04-27 00:00
[melonDS - Copy.txt](https://github.com/Arisotura/melonDS/files/6381025/melonDS.-.Copy.txt)

**Comment by WaluigiWare64** [comment] 2021-08-02 19:49
fixed by 946eb7a834e1d452ed17a9ab5d76bcf55211e54d

**Closed by WaluigiWare64** 2021-08-02 19:49 UTC
