### ISSUE TITLE
Noticeable Lag While Saving

### ISSUE THREAD

**Issue by JMC47** [Arisotura/melonDS#477] opened 2019-06-26 21:25 UTC
It appears that melonDS does not asynchronously write savefiles, as whenever games like Mario Kart DS save a ghost file, my framerate drops tremendously.  The issue disappears if I move the game/save to a solidstate harddrive.

Other emulators have asynchronous flushing to file to prevent issues like this.

**Comment by Arisotura** [comment] 2019-06-27 21:33
good point

**Comment by nathanielcwm** [comment] 2019-08-16 05:55
It's noticeable in Ace Attorney as well

**Comment by Zettymaster** [comment] 2019-08-16 15:06
Noticable in Pokémon Platinum as well.

**Comment by RSDuck** [comment] 2019-08-25 11:14
for some games like 4th gen Pokemon games you have to keep in mind that it taxes the CPU more than usually during saving, because it does encryption and what not on the save file. For some reason that's not the case for 5th gen Pokemon games, I guess they've optimised it at that point (it's also far quicker).

**Comment by Liger0** [comment] 2020-04-22 16:52
It also slows down on 5th gen, although less.

**Comment by ichee** [comment] 2020-11-12 09:28
62e3f41 seems to fix this issue, though I don't have all reported games to test with.

Castlevania Dawn of Sorrow was affected as well, but not after this commit.

**Comment by RSDuck** [comment] 2020-11-12 10:51
https://github.com/Arisotura/melonDS/commit/62e3f41f20866388287329218810d2fd8cea3515 still didn't really fix it completely (as the IO operations are still completely synchronous), though I'm happy to hear that this change atleast alleviated the problem is some games.

**Comment by RSDuck** [comment] 2021-01-25 17:10
fixed with https://github.com/Arisotura/melonDS/pull/925

**Closed by RSDuck** 2021-01-25 17:10 UTC
